services:
  - type: web
    name: house-price-prediction
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
